"""empty message

Revision ID: 60ccb89d55a5
Revises: 
Create Date: 2025-10-23 00:02:04.260075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ccb89d55a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_phone_verified')
        batch_op.drop_column('phone_otp')
        batch_op.drop_column('otp_expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('phone_otp', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('is_phone_verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
